### ISSUE TITLE
Can’t work with prysm’s power module

### ISSUE THREAD

**Issue by ghost** [cbyrne/Dismisser#1]
When touch ldrestart in power module, and touch behind alert, it still ldrestart, for other operations in power module performed the same

**Comment by conorthedev** [comment]
Can you try the latest update and see if the issue persists?

**Comment by ghost** [comment]
Thank you for your reply, it can be canceled by cancel button now, but still can’t dismiss by touching other place
2020年6月12日 +0800 PM9:47 Conor <notifications@github.com>

**Comment by conorthedev** [comment]
Contact the Prysm developer, they don't seem to be using UIAlertActionStyle properly.
